checksumBehavior: update

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/check-node-version.cjs
    spec: "https://raw.githubusercontent.com/Akryum/yarn-check-node/main/bundle/check-node-version.js"
