name: Build and Test Packages
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v18.12.1"
      - name: Enable Corepack
        run: corepack enable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          yarn install
      - run: |
          yarn lint
      - run: |
          yarn prettier:check
      - run: |
          yarn build
